wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1664831023.086109
    t:
      1:
      - 55
      3:
      - 23
      4: 3.8.9
      5: 0.13.3
      8:
      - 5
