name: week-1-ci

on:
  push:
    branches:
      - 'master'
      - 'HW2.1.1'
    env:

jobs:
  build-and-push-app-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ikosovych
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: week-1/
          file: week-1/Dockerfile
          push: true
          tags: ikosovych/week-1:latest    
          cache-from: type=registry,ref=ikosovych/week-1:buildcache
          cache-to: type=registry,ref=ikosovych/week-1:buildcache,mode=max
